#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>

#include "flags.h"

#define optpush(opt, arg) do {                                                \
  opt.count++;                                                                \
  if (!(opt.args = realloc(opt.args, sizeof(char*) * opt.count))) return '@'; \
  opt.args[opt.count-1] = arg;                                                \
} while (0)

int parseoptind, parseopterr = 1;
struct flags flags[64];

int parseopts(int argc, char *argv[], const char *program, struct opts options) {
  char *valid = ":-ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789#",
       *opts = options.shortopts;
  if (strlen(opts) != strspn(opts, valid)) return -1;
  valid++;
  if (*opts == ':') {
    opts++;
    parseopterr = 0;
  }
  if (*opts == ':') return -1;
  char *ptr;
  if ((ptr = strchr(program, '_'))) program = ptr + 1;

  int64_t needarg = 0;
  int i, j;
  for (i = 0; opts[i]; i++)
    if (opts[i+1] == ':') needarg |= 1 << opt(opts[i]);

  char c;
  for (i = 0; i < argc && argv[i][0] == '-' && argv[i][1]; i++) {
    if (argv[i][1] == '-' && !argv[i][2]) {
      i++;
      break;
    }
    if (!strcmp("--help", argv[i])) {
      /* autogenerated docs are better than no docs */
      if (options.descr) printf("%s: %s\n", program, options.descr);
      printf("%s ", program);
      if (options.help) puts(options.help);
      else {
        int brkt = 0;
        for (i = 0; opts[i]; i++) {
          if (opts[i] == '#') {
            printf("%s-num] ", brkt ? "] [" : "[");
            brkt = 0;
          }
          else if (opts[i+1] == ':') {
            printf("%s-%c arg] ", brkt ? "] [" : "[", opts[i++]);
            brkt = 0;
          }
          else {
            printf("%s%c", brkt ? "" : "[-", opts[i]);
            brkt = 1;
          }
        }
        if (brkt) printf("] ");

        i = 1;
        if (options.argleast > 0)        /* needed args */
          for (; i <= options.argleast; i++)
            printf("arg%d ", i);
        if (options.arglessthan > 0) {   /* less than lessthan args */
          for (; i < options.arglessthan; i++)
            printf("[arg%d] ", i);
        }
        else printf("[arg...]");

        putchar('\n');
      }
      return 'h';
    }
    /* parse numeric options like head -6232345 
     * todo: floats? */
    if (strchr(opts, '#') &&
        strlen(argv[i]+1+(argv[i][1] == '-')) == 
        strspn(argv[i]+1+(argv[i][1] == '-'), "0123456789")) {
      optpush(flags[opt('#')], &argv[i][1]);
      continue;
    }
    for (j = 1; (c = argv[i][j]); j++) {
      if (strchr(opts, c)) {
        if (needarg & 1 << opt(c)) {
               if (argv[i][j+1]) optpush(flags[opt(c)], &argv[i][j+1]);
          else if (++i < argc)   optpush(flags[opt(c)], &argv[i][0]);
          else {
            if (parseopterr) fprintf(stderr, "%s: Missing argument for option: -%c\n", program, c);
            return ':';
          }
          break;
        }
        else flags[opt(c)].count++;
      }
      else {
        if (parseopterr) fprintf(stderr, "%s: Unknown option: -%c\n", program, c);
        return '?';
      }
    }
  }
  parseoptind = i;
  return 0;
}
